---

- name: Install Pip
  become: true
  dnf:
    name:
      - python-pip
    state: latest

- name: Upgrade/Install Python packages (Ansible requirements)
  pip: 
    name:
      - github3.py
    state: latest

- name: Get Scriptured Prayer Latest Release
  register: release_version
  community.general.github_release:
    user: "{{ github_user }}"
    repo: "{{ github_repo }}"
    action: latest_release

- name: Set project_path to the latest release # eventually or current branch
  set_fact:
    project_path: "/var/gunicorn/scriptured-prayer-{{ release_version.tag }}"

- name: "Find out if PostgreSQL is initialized"
  become: true
  stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Ensure the PostgreSQL service is running
  become: true
  service: name=postgresql state=started enabled=yes
  when: postgres_data.stat.exists

- name: Check if the PostgreSQL database exists
  become: true
  become_user: postgres
  postgresql_info:
    filter: databases
  register: postgres_db_info
  when: postgres_data.stat.exists

# The organization of this ansible playbook makes this tricky. This will always skip when it runs for the gunicorn role
# but new_db will be set to true when it runs for the postgres role. This is because the postgres role runs first and sets new_db to true
- name: Set new_db
  set_fact:
    new_db: True
  when: not postgres_data.stat.exists or (db_name not in postgres_db_info.databases)
