---

- name: restart application
  become: true
  supervisorctl: name={{ project_name }} state=restarted

- name: restart nginx
  become: true
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  become: true
  service: name=nginx state=reloaded

- name: Re-read the Supervisor config files
  become: true
  supervisorctl: name={{ project_name }} state=present

- name: Restart Supervisor
  become: true
  supervisorctl: name={{ project_name }} state=restarted