# Generated by Django 4.2.8 on 2023-12-17 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NG", "Names of God"),
                            ("GI", "God Is ..."),
                            ("NJ", "Names of Jesus"),
                            ("NS", "Names of the Holy Spirit"),
                            ("IC", "In Christ"),
                            ("PG", "Promises of God"),
                            ("SR", "Stones of Remembrance"),
                            ("BP", "Breath Prayers"),
                            ("PR", "Prayers of the Bible"),
                        ],
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_es", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("scripture", models.CharField(max_length=50)),
                ("scripture_es", models.CharField(max_length=50, null=True)),
                ("scripture_en", models.CharField(max_length=50, null=True)),
                ("text", models.CharField(max_length=500)),
                ("text_es", models.CharField(max_length=500, null=True)),
                ("text_en", models.CharField(max_length=500, null=True)),
                ("private", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="date created"),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_count", models.IntegerField(default=0)),
                ("count_adjustment", models.IntegerField(default=0)),
                ("answered", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cardbox.card"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "card")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("cards_per_day", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserCardNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(max_length=200)),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "usercard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardbox.usercard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCategorySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NG", "Names of God"),
                            ("GI", "God Is ..."),
                            ("NJ", "Names of Jesus"),
                            ("NS", "Names of the Holy Spirit"),
                            ("IC", "In Christ"),
                            ("PG", "Promises of God"),
                            ("SR", "Stones of Remembrance"),
                            ("BP", "Breath Prayers"),
                            ("PR", "Prayers of the Bible"),
                        ],
                        max_length=2,
                    ),
                ),
                ("sun", models.BooleanField(default=False)),
                ("mon", models.BooleanField(default=False)),
                ("tue", models.BooleanField(default=False)),
                ("wed", models.BooleanField(default=False)),
                ("thu", models.BooleanField(default=False)),
                ("fri", models.BooleanField(default=False)),
                ("sat", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category")},
            },
        ),
        migrations.CreateModel(
            name="PrayerUserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "prayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cardbox.prayer"
                    ),
                ),
                (
                    "usercard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardbox.usercard",
                    ),
                ),
            ],
            options={
                "unique_together": {("prayer", "usercard")},
            },
        ),
    ]
