# Generated by Django 4.2.8 on 2023-12-26 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cardbox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerDeck",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created timestamp"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCardPrayedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_prayed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date prayed"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCategoryOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NG", "Names of God"),
                            ("GI", "God Is ..."),
                            ("NJ", "Names of Jesus"),
                            ("NS", "Names of the Holy Spirit"),
                            ("IC", "In Christ"),
                            ("PG", "Promises of God"),
                            ("SR", "Stones of Remembrance"),
                            ("BP", "Breath Prayers"),
                            ("PR", "Prayers of the Bible"),
                        ],
                        max_length=2,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("pray_all_cards", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="prayerusercard",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="prayerusercard",
            name="prayer",
        ),
        migrations.RemoveField(
            model_name="prayerusercard",
            name="usercard",
        ),
        migrations.AlterUniqueTogether(
            name="usercategoryschedule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usercategoryschedule",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usercard",
            name="count_adjustment",
        ),
        migrations.RemoveField(
            model_name="usercard",
            name="use_count",
        ),
        migrations.AlterField(
            model_name="usercardnote",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created timestamp"
            ),
        ),
        migrations.DeleteModel(
            name="Prayer",
        ),
        migrations.DeleteModel(
            name="PrayerUserCard",
        ),
        migrations.DeleteModel(
            name="UserCategorySchedule",
        ),
        migrations.AddField(
            model_name="usercardprayedlog",
            name="usercard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cardbox.usercard"
            ),
        ),
        migrations.AddField(
            model_name="usercard",
            name="prayerdeck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cardbox.prayerdeck",
            ),
        ),
    ]
