---

- name: restart application
  become: true
  supervisorctl: name={{ project_name }} state=restarted

- name: Re-read the Supervisor config files
  become: true
  supervisorctl: name={{ project_name }} state=present

- name: Restart Supervisor
  become: true
  supervisorctl: name={{ project_name }} state=restarted