# Generated by Django 4.2.9 on 2024-01-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='text_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='text_es',
            new_name='description_es',
        ),
    ]
