# Generated by Django 5.1 on 2024-08-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prayerapp", "0003_card_instruction_en_card_instruction_es_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="card",
            name="description_es",
        ),
        migrations.RemoveField(
            model_name="card",
            name="instruction_en",
        ),
        migrations.RemoveField(
            model_name="card",
            name="instruction_es",
        ),
        migrations.RemoveField(
            model_name="card",
            name="scripture_en",
        ),
        migrations.RemoveField(
            model_name="card",
            name="scripture_es",
        ),
        migrations.RemoveField(
            model_name="card",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="card",
            name="title_es",
        ),
        migrations.RemoveField(
            model_name="card",
            name="version_en",
        ),
        migrations.RemoveField(
            model_name="card",
            name="version_es",
        ),
        migrations.RemoveField(
            model_name="category",
            name="default_instruction_en",
        ),
        migrations.RemoveField(
            model_name="category",
            name="default_instruction_es",
        ),
        migrations.RemoveField(
            model_name="category",
            name="inspiration_en",
        ),
        migrations.RemoveField(
            model_name="category",
            name="inspiration_es",
        ),
        migrations.RemoveField(
            model_name="category",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="category",
            name="name_es",
        ),
    ]
