# Generated by Django 5.1.2 on 2024-10-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerapp', '0004_remove_card_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='genre',
            field=models.CharField(choices=[('PR', 'Praise'), ('RQ', 'Request'), ('CF', 'Confession'), ('TG', 'Thanksgiving'), ('UT', 'Utility')], max_length=2),
        ),
    ]
